In [2]:
import pandas as pd
import os
import re
from functools import reduce

In [3]:
gdp=pd.read_csv('gdp_all_year.csv')
pce=pd.read_csv('pce_all_year.csv')
pi=pd.read_csv('pi_all_year.csv')
target=pd.read_csv('target.csv')

In [29]:
target['year']=target['year'].astype(int)

In [30]:
dfs = [gdp, pce, pi]
from functools import reduce
df_final = reduce(lambda left,right: pd.merge(left,right,on=['GeoName','year']), dfs)

In [17]:
df_final.head(5)

,GeoName,year,Compensation of employees,Gross domestic product (GDP) by state,Gross operating surplus,Per capita real GDP by state,Quantity indexes for real GDP by state,Real GDP by state,Subsidies,Taxes on production and imports,...,Income taxes (net of refunds),Other taxes,Other taxes,Federal government,Less: Personal current taxes,Local governments,State and local personal property taxes,State governments,Equals: Disposable personal income,Personal current taxes
0,Alabama,1997,61240,104309.0,36814,31465.0,81.042,137437.0,-328,6582,...,8558198.0,40573.0,15957.0,8558198.0,10612417.0,136089.0,44757.0,1873373.0,83209782.0,10612417.0
1,Alaska,1997,12205,25763.0,11234,62577.0,75.935,38358.0,-62,2386,...,1797971.0,1705.0,15139.0,1797971.0,1844364.0,4999.0,2786.0,38608.0,15203610.0,1844364.0
2,Arizona,1997,69886,132795.0,54249,34485.0,67.195,163353.0,-383,9044,...,10868970.0,16187.0,21430.0,10868970.0,12903928.0,17978.0,163562.0,1853418.0,94533284.0,12903928.0
3,Arkansas,1997,32852,60248.0,23415,30470.0,79.178,79256.0,-298,4279,...,4292918.0,3048.0,22535.0,4292918.0,5709269.0,3048.0,30510.0,1382793.0,46699786.0,5709269.0
4,California,1997,574394,1082051.0,441963,41314.0,70.134,1342133.0,-5725,71419,...,93479407.0,319603.0,69778.0,93479407.0,120765010.0,319603.0,1362268.0,25603732.0,761138752.0,120765010.0

In [31]:
target=target.groupby(['state','year']).sum().reset_index()
df_final=pd.merge(df_final,target,left_on=['GeoName','year'],right_on=['state','year'])

In [32]:
df_final.shape

(1017, 200)

In [33]:
df_final.to_csv('all_year.csv',index=False)

In [14]:
industry=pd.read_table('C:/Users/ttodd/OneDrive/Desktop/capstone/static_st_3det_ind_11_0.txt',sep=',')

In [38]:
industry

,Year,State,firm type,NAICS,Total,<20,20-99,100-499,500+,<500
0,2011.0,Alabama,firm,113,591,547,38,1,5,586
1,2011.0,Alabama,firm,114,22,21,1,NaN,NaN,22
2,2011.0,Alabama,firm,115,170,148,10,5,7,163
3,2011.0,Alabama,firm,211,31,17,1,NaN,13,18
4,2011.0,Alabama,firm,212,93,54,19,5,15,78
5,2011.0,Alabama,firm,213,72,41,12,7,12,60
6,2011.0,Alabama,firm,221,107,63,19,5,20,87
7,2011.0,Alabama,firm,236,2130,1963,133,8,26,2104
8,2011.0,Alabama,firm,237,640,506,95,19,20,620
9,2011.0,Alabama,firm,238,4873,4353,422,57,41,4832
10,2011.0,Alabama,firm,311,226,139,29,22,36,190
11,2011.0,Alabama,firm,312,29,21,2,NaN,6,23
12,2011.0,Alabama,firm,313,34,14,9,2,9,25
13,2011.0,Alabama,firm,314,99,75,12,5,7,92
14,2011.0,Alabama,firm,315,52,35,12,3,2,50
15,2011.0,Alabama,firm,316,14,14,NaN,NaN,NaN,14
16,2011.0,Alabama,firm,321,316,167,89,33,27,289
17,2011.0,Alabama,firm,322,47,11,13,4,19,28
18,2011.0,Alabama,firm,323,349,303,36,3,7,342
19,2011.0,Alabama,firm,324,28,8,7,5,8,20
20,2011.0,Alabama,firm,325,151,55,26,28,42,109
21,2011.0,Alabama,firm,326,163,65,37,28,33,130
22,2011.0,Alabama,firm,327,186,116,27,14,29,157
23,2011.0,Alabama,firm,331,98,32,22,16,28,70
24,2011.0,Alabama,firm,332,898,599,187,52,60,838
25,2011.0,Alabama,firm,333,252,138,56,26,32,220
26,2011.0,Alabama,firm,334,109,60,23,7,19,90
27,2011.0,Alabama,firm,335,64,36,15,3,10,54
28,2011.0,Alabama,firm,336,244,96,49,39,60,184
29,2011.0,Alabama,firm,337,287,233,30,12,12,275
...,...,...,...,...,...,...,...,...,...,...
245872,1998.0,Wyoming,ann. pay.,492,4749,D,D,NaN,D,D
245873,1998.0,Wyoming,ann. pay.,493,904,904,NaN,NaN,NaN,904
245874,1998.0,Wyoming,ann. pay.,511,D,D,D,D,D,D
245875,1998.0,Wyoming,ann. pay.,512,D,D,D,NaN,D,D
245876,1998.0,Wyoming,ann. pay.,513,68421,11577,7291,D,D,D
245877,1998.0,Wyoming,ann. pay.,514,4273,1518,D,NaN,D,D
245878,1998.0,Wyoming,ann. pay.,522,D,D,D,12917,D,55071
245879,1998.0,Wyoming,ann. pay.,523,D,D,D,D,D,20492
245880,1998.0,Wyoming,ann. pay.,524,58019,D,D,D,15189,42830
245881,1998.0,Wyoming,ann. pay.,525,D,NaN,NaN,NaN,D,NaN
245882,1998.0,Wyoming,ann. pay.,531,D,D,D,D,D,D
245883,1998.0,Wyoming,ann. pay.,532,D,D,D,D,D,D
245884,1998.0,Wyoming,ann. pay.,533,D,D,NaN,D,D,D
245885,1998.0,Wyoming,ann. pay.,541,171034,108376,43339,6287,13032,158002
245886,1998.0,Wyoming,ann. pay.,551,58023,D,D,D,42481,15542
245887,1998.0,Wyoming,ann. pay.,561,73480,D,D,D,24698,48782
245888,1998.0,Wyoming,ann. pay.,562,6070,D,D,D,2728,3342
245889,1998.0,Wyoming,ann. pay.,611,19536,D,D,D,D,D
245890,1998.0,Wyoming,ann. pay.,621,193394,D,D,D,18936,174458
245891,1998.0,Wyoming,ann. pay.,622,249956,D,D,D,D,D
245892,1998.0,Wyoming,ann. pay.,623,53384,D,D,D,D,D
245893,1998.0,Wyoming,ann. pay.,624,59781,D,D,25530,3686,56095
245894,1998.0,Wyoming,ann. pay.,711,D,D,D,NaN,NaN,D
245895,1998.0,Wyoming,ann. pay.,712,D,D,D,D,NaN,D
245896,1998.0,Wyoming,ann. pay.,713,27986,D,D,D,D,D
245897,1998.0,Wyoming,ann. pay.,721,94346,22045,24730,21608,25963,68383
245898,1998.0,Wyoming,ann. pay.,722,142580,42261,60937,17897,21485,121095
245899,1998.0,Wyoming,ann. pay.,811,D,D,D,D,D,D
245900,1998.0,Wyoming,ann. pay.,812,D,D,D,D,D,D
245901,1998.0,Wyoming,ann. pay.,813,D,D,D,D,D,D

In [33]:
industry.columns=['Year', 'State', 'firm type', 'NAICS', 'Total','<20', '20-99', '100-499', '500+', '<500']
industry_fillna=industry.loc[:,['Year','State','firm type']]
industry_fillna=industry_fillna.fillna(method='ffill')
industry.loc[:,['Year','State','firm type']]=industry_fillna

In [35]:
industry.to_csv('industry_target.csv',index=False)

In [37]:
industry['firm type'].value_counts()

emp.         60375
est.         60375
firms        38606
ann. pay.    38606
firm         21769
pay.         21769
rec.          4402
Name: firm type, dtype: int64

In [23]:
core = df_final.corr() # df is the pandas dataframe
c1 = core.abs().unstack()
c1=c1[c1<=0.9]
c1.sort_values(ascending = False)

Veterans' benefits                                                                        Supplemental Nutrition Assistance Program (SNAP)                                            8.999955e-01
Supplemental Nutrition Assistance Program (SNAP)                                          Veterans' benefits                                                                          8.999955e-01
Real GDP by state                                                                         Earned Income Tax Credit (EITC)                                                             8.999320e-01
Earned Income Tax Credit (EITC)                                                           Real GDP by state                                                                           8.999320e-01
pce Less: Receipts from sales of goods and services by nonprofit institutions             Per capita net earnings                                                                     8.997622e-01
Per capita net earnings                                                                   pce Less: Receipts from sales of goods and services by nonprofit institutions               8.997622e-01
Monetary rent                                                                             Less: Contributions for government social insurance                                         8.997057e-01
Less: Contributions for government social insurance                                       Monetary rent                                                                               8.997057e-01
Per capita personal current transfer receipts                                             year                                                                                        8.997042e-01
year                                                                                      Per capita personal current transfer receipts                                               8.997042e-01
Medicaid                                                                                  Receipts from the Federal government                                                        8.994615e-01
Receipts from the Federal government                                                      Medicaid                                                                                    8.994615e-01
Social Security benefits                                                                  Public assistance medical care benefits                                                     8.994229e-01
Public assistance medical care benefits                                                   Social Security benefits                                                                    8.994229e-01
Other income maintenance benefits                                                         Wage and salary employment                                                                  8.994112e-01
Wage and salary employment                                                                Other income maintenance benefits                                                           8.994112e-01
Rental income of persons                                                                  Supplements to wages and salaries                                                           8.993871e-01
Supplements to wages and salaries                                                         Rental income of persons                                                                    8.993871e-01
Rental income of persons                                                                  Supplements to wages and salaries                                                           8.993871e-01
Supplements to wages and salaries                                                         Rental income of persons                                                                    8.993871e-01
Income taxes (gross)                                                                      Education and training assistance 1                                                         8.991741e-01
Education and training assistance 1                                                       Income taxes (gross)                                                                        8.991741e-01
pce  Nondurable goods                                                                     pcePersonal consumption expenditures                                                        8.990155e-01
pcePersonal consumption expenditures                                                      pce  Nondurable goods                                                                       8.990155e-01
Earned Income Tax Credit (EITC)                                                           Employer contributions for employee pension and insurance funds                             8.988977e-01
Employer contributions for employee pension and insurance funds                           Earned Income Tax Credit (EITC)                                                             8.988977e-01
Nonfarm proprietors' income                                                               Excluding family assistance                                                                 8.988679e-01
Excluding family assistance                                                               Nonfarm proprietors' income                                                                 8.988679e-01
Education and training assistance 1                                                       Monetary rent                                                                               8.987846e-01
Monetary rent                                                                             Education and training assistance 1                                                         8.987846e-01
                                                                                                                                                                                          ...
Equals: Net income including corporate farms                                              pce  Nondurable goods                                                                       6.371029e-04
pce  Nondurable goods                                                                     Equals: Net income including corporate farms                                                6.371029e-04
Farm proprietors' income                                                                  pce Gross output of nonprofit institutions                                                  5.646665e-04
Equals: Farm proprietors' income                                                          pce Gross output of nonprofit institutions                                                  5.646665e-04
pce Gross output of nonprofit institutions                                                Farm proprietors' income                                                                    5.646665e-04
                                                                                          Equals: Farm proprietors' income                                                            5.646665e-04
Tobacco                                                                                   Plus: Adjustment for residence                                                              4.029911e-04
Plus: Adjustment for residence                                                            Tobacco                                                                                     4.029911e-04
All other production expenses                                                             pce  Housing and utilities                                                                  3.948007e-04
pce  Housing and utilities                                                                All other production expenses                                                               3.948007e-04
Plus: Farm supplements to wages and salaries                                              Per capita retirement and other                                                             3.860243e-04
Per capita retirement and other                                                           Plus: Farm supplements to wages and salaries                                                3.860243e-04
Tobacco                                                                                   Petroleum products purchased                                                                2.798918e-04
Petroleum products purchased                                                              Tobacco                                                                                     2.798918e-04
pce  Durable goods                                                                        Wage and salary employment                                                                  2.786850e-04
Wage and salary employment                                                                pce  Durable goods                                                                          2.786850e-04
Less: Refunds                                                                             pce Final consumption expenditures of nonprofit institutions serving households (NPISHs)    2.083297e-04
pce Final consumption expenditures of nonprofit institutions serving households (NPISHs)  Less: Refunds                                                                               2.083297e-04
Plus: Adjustment for residence                                                            pce  Housing and utilities                                                                  1.979113e-04
pce  Housing and utilities                                                                Plus: Adjustment for residence                                                              1.979113e-04
pce   Gasoline and other energy goods                                                     Veterans' readjustment benefits                                                             1.689042e-04
Veterans' readjustment benefits                                                           pce   Gasoline and other energy goods                                                       1.689042e-04
Hay, silage, etc.                                                                         pce  Nondurable goods                                                                       1.433062e-04
pce  Nondurable goods                                                                     Hay, silage, etc.                                                                           1.433062e-04
Livestock purchased                                                                       State governments                                                                           1.276157e-04
State governments                                                                         Livestock purchased                                                                         1.276157e-04
Quantity indexes for real GDP by state                                                    Plus: Adjustment for residence                                                              8.908612e-05
Plus: Adjustment for residence                                                            Quantity indexes for real GDP by state                                                      8.908612e-05
Tobacco                                                                                   Other income maintenance benefits                                                           1.497720e-07
Other income maintenance benefits                                                         Tobacco                                                                                     1.497720e-07
Length: 24762, dtype: float64

In [22]:
df_final.columns

Index(['GeoName', 'year', 'Compensation of employees',
       'Gross domestic product (GDP) by state', 'Gross operating surplus',
       'Per capita real GDP by state',
       'Quantity indexes for real GDP by state', 'Real GDP by state',
       'Subsidies', 'Taxes on production and imports',
       ...
       'Income taxes (net of refunds) ', 'Other taxes', 'Other taxes ',
       'Federal government ', 'Less: Personal current taxes',
       'Local governments', 'State and local personal property taxes',
       'State governments', 'Equals: Disposable personal income',
       'Personal current taxes'],
      dtype='object', length=192)